package com.hyphenate.easeui.model;

import com.hyphenate.easeui.R;
import com.hyphenate.easeui.domain.EaseEmojicon;
import com.hyphenate.easeui.domain.EaseEmojicon.Type;
import com.hyphenate.easeui.utils.EaseSmileUtils;

public class EaseDefaultEmojiconDatas {
    
    private static String[] emojis = new String[]{
        EaseSmileUtils.ee_1,
        EaseSmileUtils.ee_2,
        EaseSmileUtils.ee_3,
        EaseSmileUtils.ee_4,
        EaseSmileUtils.ee_5,
        EaseSmileUtils.ee_6,
        EaseSmileUtils.ee_7,
        EaseSmileUtils.ee_8,
        EaseSmileUtils.ee_9,
        EaseSmileUtils.ee_10,
        EaseSmileUtils.ee_11,
        EaseSmileUtils.ee_12,
        EaseSmileUtils.ee_13,
        EaseSmileUtils.ee_14,
        EaseSmileUtils.ee_15,
        EaseSmileUtils.ee_16,
        EaseSmileUtils.ee_17,
        EaseSmileUtils.ee_18,
        EaseSmileUtils.ee_19,
        EaseSmileUtils.ee_20,
        EaseSmileUtils.ee_21,
        EaseSmileUtils.ee_22,
        EaseSmileUtils.ee_23,
        EaseSmileUtils.ee_24,
        EaseSmileUtils.ee_25,
        EaseSmileUtils.ee_26,
        EaseSmileUtils.ee_27,
        EaseSmileUtils.ee_28,
        EaseSmileUtils.ee_29,
        EaseSmileUtils.ee_30,
        EaseSmileUtils.ee_31,
        EaseSmileUtils.ee_32,
        EaseSmileUtils.ee_33,
        EaseSmileUtils.ee_34,
        EaseSmileUtils.ee_35,
       
    };
    
    private static int[] icons = new int[]{
        R.drawable.emoij_001,
        R.drawable.emoij_002,
        R.drawable.emoij_003,
        R.drawable.emoij_004,
        R.drawable.emoij_005,
        R.drawable.emoij_006,
        R.drawable.emoij_007,
        R.drawable.emoij_008,
        R.drawable.emoij_009,
        R.drawable.emoij_010,
        R.drawable.emoij_011,
        R.drawable.emoij_012,
        R.drawable.emoij_013,
        R.drawable.emoij_014,
        R.drawable.emoij_015,
        R.drawable.emoij_016,
        R.drawable.emoij_017,
        R.drawable.emoij_018,
        R.drawable.emoij_019,
        R.drawable.emoij_020,
        R.drawable.emoij_021,
        R.drawable.emoij_022,
        R.drawable.emoij_023,
        R.drawable.emoij_024,
        R.drawable.emoij_025,
        R.drawable.emoij_026,
        R.drawable.emoij_027,
        R.drawable.emoij_028,
        R.drawable.emoij_029,
        R.drawable.emoij_030,
        R.drawable.emoij_031,
        R.drawable.emoij_032,
        R.drawable.emoij_033,
        R.drawable.emoij_034,
        R.drawable.emoij_035,
//        R.drawable.emoij_036,
//        R.drawable.emoij_037,
////        R.drawable.emoij_038,
////        R.drawable.emoij_039,
//        R.drawable.emoij_040,
//        R.drawable.emoij_041,
//        R.drawable.emoij_042,
//        R.drawable.emoij_043,
//        R.drawable.emoij_044,
//        R.drawable.emoij_045,
//        R.drawable.emoij_046,
//        R.drawable.emoij_047,
//        R.drawable.emoij_048,
//        R.drawable.emoij_049,
//        R.drawable.emoij_050,
//        R.drawable.emoij_051,
//        R.drawable.emoij_052,
//        R.drawable.emoij_053,
//        R.drawable.emoij_054,
//        R.drawable.emoij_055,
////        R.drawable.emoij_056,
//        R.drawable.emoij_057,
//        R.drawable.emoij_058,
//        R.drawable.emoij_059,
////        R.drawable.emoij_060,
//        R.drawable.emoij_061,
////        R.drawable.emoij_062,
//        R.drawable.emoij_063,
////        R.drawable.emoij_064,
////        R.drawable.emoij_065,
//        R.drawable.emoij_066,
//        R.drawable.emoij_067,
//        R.drawable.emoij_068,
////        R.drawable.emoij_069,
////        R.drawable.emoij_070,
//        R.drawable.emoij_071,
////        R.drawable.emoij_072,
//        R.drawable.emoij_073,
////        R.drawable.emoij_074,
//        R.drawable.emoij_075,
////        R.drawable.emoij_076,
////        R.drawable.emoij_077,
////        R.drawable.emoij_078,
//        R.drawable.emoij_079,
////        R.drawable.emoij_080,
////        R.drawable.emoij_081,
////        R.drawable.emoij_082,
//        R.drawable.emoij_083,
////        R.drawable.emoij_084,
//        R.drawable.emoij_085,
//        R.drawable.emoij_086,
//        R.drawable.emoij_087,
//        R.drawable.emoij_088,
//        R.drawable.emoij_089,
//        R.drawable.emoij_090,
//        R.drawable.emoij_091,
////        R.drawable.emoij_092,
////        R.drawable.emoij_093,
//        R.drawable.emoij_094,
////        R.drawable.emoij_095,
//        R.drawable.emoij_096,
//        R.drawable.emoij_097,
////        R.drawable.emoij_098,
//        R.drawable.emoij_099,
//        R.drawable.emoij_100,
//        R.drawable.emoij_101,
////        R.drawable.emoij_102,
//        R.drawable.emoij_103,
////        R.drawable.emoij_104,
////        R.drawable.emoij_105,
    };
    
    
    private static final EaseEmojicon[] DATA = createData();
    
    private static EaseEmojicon[] createData(){
        EaseEmojicon[] datas = new EaseEmojicon[icons.length];
        for(int i = 0; i < icons.length; i++){
            datas[i] = new EaseEmojicon(icons[i], emojis[i], Type.NORMAL);
        }
        return datas;
    }
    
    public static EaseEmojicon[] getData(){
        return DATA;
    }
}
